# Generated by Django 3.2 on 2021-04-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0002_alter_private_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private',
            name='field',
            field=models.TextField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='private',
            name='password',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
