# Generated by Django 3.2 on 2021-04-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0003_auto_20210501_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private',
            name='field',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='private',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
