# Generated by Django 3.2 on 2021-04-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0004_auto_20210501_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='private',
            name='password',
        ),
    ]
