# Generated by Django 3.2 on 2021-04-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0007_alter_private_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='private',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
