# Generated by Django 3.2 on 2021-04-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordGenerator', '0008_private_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='private',
            name='discription',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='private',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
